#ifndef APPLICATION_STATE_H
#define APPLICATION_STATE_H
enum ApplicationState { APP_STARTUP, APP_RENDER_GAME, APP_PAUSED,
						APP_GAME_LOADING, APP_SHOW_GAMERULES, APP_SHOW_GAMERULES2,
						APP_VICTORY, APP_SHOWTIMES, APP_ENTERNAME };
#endif